theme: jekyll-theme-minimal
title: Música como interdisciplina - Perspectivas e intersecções na UC
description: Programa e informações sobre o evento "Música como interdisciplina - Perspectivas e intersecções na UC", 15 de Fevereiro de 2024, CEIS20.