title: Música como interdisciplina - Perspectivas e intersecções na UC
description: Programa e informações sobre o evento "Música como interdisciplina - Perspectivas e intersecções na UC", 15 de Fevereiro de 2024, CEIS20.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme